### ISSUE TITLE
А ещё убери эту полосу прокрутки. ! то есть, прокрутка должна остаться, а сама полоса должна изчезнуть, а то выглядит по бабушкински. Попробуй найти по этому поводу статью на doka.guide.

### ISSUE THREAD

**Issue by Kirill22012002** [anastasiya1712/posmotri_v_okno#13]
![image](https://github.com/anastasiya1712/posmotri_v_okno/assets/98803274/e51e2179-11c7-4c4e-9982-a9ed01df2d60)

Либо ещё где-то. я думаю гуглить нужно как-то так: overflow scroll without scrollbar. 

Типо overflow это свойство для создания прокрутки, scroll это значение, чтобы была прокрутка, и without scrollbar, это типо, что мы хотим видеть эту штукенцию без scrollbar мне кажется он так называется:
![image](https://github.com/anastasiya1712/posmotri_v_okno/assets/98803274/23f02bc0-fe2f-46b9-ac69-0ebe59713c5b)

**Comment by anastasiya1712** [comment]
+
